/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{ts,tsx,html}'],
  // safelist: 동적으로 생성되는 클래스 (JS template literal 내부)
  safelist: [
    // 동적 색상 클래스
    { pattern: /^(bg|text|border|ring)-(red|green|blue|yellow|orange|purple|indigo|teal|gray|white|black)-(50|100|200|300|400|500|600|700|800|900)$/ },
    { pattern: /^(bg|text|border)-(red|green|blue|yellow|orange|purple|indigo|teal|gray)-(50|100|200|300|400|500|600|700|800|900)\/(10|20|30|40|50|60|70|80|90)$/ },
    // 동적 크기 클래스
    { pattern: /^(w|h|min-w|min-h|max-w|max-h)-(4|5|6|7|8|9|10|12|16|20|24|32|48|64|full|screen|fit|auto)$/ },
    { pattern: /^(p|px|py|pt|pb|pl|pr|m|mx|my|mt|mb|ml|mr)-(0|1|2|3|4|5|6|7|8|10|12|16)$/ },
    { pattern: /^(text)-(xs|sm|base|lg|xl|2xl|3xl|4xl)$/ },
    { pattern: /^(rounded|rounded-lg|rounded-xl|rounded-full|rounded-t-xl|rounded-b-xl)$/ },
    { pattern: /^(flex|grid|hidden|block|inline|inline-flex|inline-block)$/ },
    { pattern: /^(items|justify)-(start|end|center|between|around)$/ },
    { pattern: /^gap-(1|2|3|4|5|6|8)$/ },
    { pattern: /^(font)-(normal|medium|semibold|bold)$/ },
    { pattern: /^(opacity)-(0|25|50|75|100)$/ },
    { pattern: /^(transition|duration|ease)(-\w+)?$/ },
    { pattern: /^(hover|focus|active|peer-checked|group-hover):/ },
    { pattern: /^(col|row)-span-\d$/ },
    'line-through', 'underline', 'cursor-pointer', 'cursor-grab',
    'overflow-hidden', 'overflow-y-auto', 'overflow-x-hidden',
    'pointer-events-none', 'pointer-events-auto',
    'select-none', 'whitespace-nowrap', 'break-all', 'truncate',
    'sr-only', 'not-sr-only',
    'animate-spin', 'animate-pulse',
    'inset-0', 'z-50', 'z-10', 'fixed', 'absolute', 'relative', 'sticky',
    'top-0', 'left-0', 'right-0', 'bottom-0',
    'shadow', 'shadow-sm', 'shadow-md', 'shadow-lg', 'shadow-xl', 'shadow-2xl',
    'border', 'border-t', 'border-b', 'border-l', 'border-r',
    'border-2', 'border-dashed',
    'flex-1', 'flex-shrink-0', 'flex-col', 'flex-row', 'flex-wrap',
    'space-y-1', 'space-y-2', 'space-y-3', 'space-y-4', 'space-y-6',
    'space-x-1', 'space-x-2', 'space-x-3', 'space-x-4',
    'grid-cols-1', 'grid-cols-2', 'grid-cols-3',
    'leading-none', 'leading-tight', 'leading-normal',
    'max-h-40', 'max-h-60', 'max-h-24',
    'bg-white', 'bg-black',
    'text-white', 'text-black',
    'w-full', 'h-full', 'min-h-screen',
    'bg-gradient-to-r', 'from-indigo-500', 'to-purple-500',
    'from-blue-500', 'to-indigo-500',
    'from-green-500', 'to-emerald-500',
    'from-purple-500', 'to-pink-500',
    'from-teal-500', 'to-cyan-500',
    'from-orange-500', 'to-red-500',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
